openapi: 3.0.1
info:
  title: MZT Health Fitness App
  description: A webapp to assist a coach in managing their client's workout programs.
  version: 0.0.1
servers:
- url: /
paths:
  /customer/getCustomerById/{customer_id}:
    get:
      description: Gets all customer information by customer ID
      operationId: getCustomerById
      parameters:
      - $ref: '#/components/parameters/customerIdParamGet'
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/getAllCustomers:
    get:
      description: Gets list of all customers
      operationId: getAllCustomers
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/addCustomer:
    post:
      description: Creates new customer
      operationId: addCustomer
      requestBody:
        description: Add a new customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/updateCustomer:
    post:
      description: Updates an existing customer
      operationId: updateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        200:
          description: OK Customer Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/deleteCustomer:
    delete:
      description: Deletes an existing customer
      operationId: deleteCustomer
      parameters:
        - $ref: '#/components/parameters/customerIdParamDel'
      responses:
        200:
          description: OK Customer Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/customerIdParamDel'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/getCustomerMeasurementsById/{customer_id}:
    get:
      description: Gets list of a customer's measurements by their id. This returns
        multiple measurements if there exists more than 1
      operationId: getCustomerMeasurementsById
      parameters:
      - $ref: '#/components/parameters/customerIdParamGet'
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: measurement.controller
  /customer/addMeasurement:
    post:
      description: Create a new customer's measurement
      operationId: addMeasurement
      requestBody:
        description: Add a new customer's measurement
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: measurement.controller
  /program/getProgramById/{program_id}:
    get:
      description: Gets all program information by program ID
      operationId: getProgramById
      parameters:
      - $ref: '#/components/parameters/programIdParamGet'
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /program/getProgramByCustomerId/{customer_id}:
    get:
      description: Gets all program information by customer ID
      operationId: getProgramByCustomerId
      parameters:
      - $ref: '#/components/parameters/customerIdParamGet'
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /program/getAllPrograms:
    get:
      description: Gets list of all programs
      operationId: getAllPrograms
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /program/addProgram:
    post:
      description: Creates new program
      operationId: addProgram
      requestBody:
        description: Add a new program
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Program'
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /program/updateProgram:
    post:
      description: Updates an existing program
      operationId: updateProgram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Program'
      responses:
        200:
          description: OK Program Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /program/deleteProgram:
    delete:
      description: Deletes an existing program
      operationId: deleteProgram
      parameters:
        - $ref: '#/components/parameters/programIdParamDel'
      responses:
        200:
          description: OK Program Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/programIdParamDel'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: program.controller
  /exercise/getAllExercises:
    get:
      description: Gets list of all exercises
      operationId: getAllExercises
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/getExerciseById/{exercise_id}:
    get:
      description: Gets an exercise by ID
      operationId: getExerciseById
      parameters:
      - $ref: '#/components/parameters/exerciseIdParamGet'
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/addExercise:
    post:
      description: Creates new exercise
      operationId: addExercise
      requestBody:
        description: Add a new exercise
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/updateExercise:
    post:
      description: Updates an existing exercise
      operationId: updateExercise
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        200:
          description: OK Exercise Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/deleteExercise:
    delete:
      description: Deletes an existing exercise
      operationId: deleteExercise
      parameters:
        - $ref: '#/components/parameters/exerciseIdParamDel'
      responses:
        200:
          description: OK Exercise Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/exerciseIdParamDel'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller     
  /session/getAllSessionsByProgId/{program_id}:
    get:
      description: Gets a session by program ID
      operationId: getAllSessionsByProgId
      parameters:
      - $ref: '#/components/parameters/programIdParamGet'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /session/getSessionById/{session_id}:
    get:
      description: Gets an session by ID
      operationId: getSessionById
      parameters:
      - $ref: '#/components/parameters/sessionIdParamGet'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /session/assignExercise:
    post:
      description: Assigns exercises to session
      operationId: assignExercise
      requestBody:
        description: Assigns exercises to session
        required: true
        content:
          application/json:
            schema:
               $ref: '#/components/parameters/sessionIdParamAssign'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /session/addSession:
    post:
      description: Creates new session
      operationId: addSession
      requestBody:
        description: Add a new session
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /session/updateSession:
    post:
      description: Updates an existing session
      operationId: updateSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        200:
          description: OK Session Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /session/deleteSession:
    delete:
      description: Deletes an existing session
      operationId: deleteSession
      parameters:
        - $ref: '#/components/parameters/sessionIdParamDel'
      responses:
        200:
          description: OK session Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/sessionIdParamDel'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: session.controller
  /sessionTemplate/getAllSessionTempByProgId/{program_id}:
    get:
      description: Gets a session template by program ID
      operationId: getAllSessionTempByProgId
      parameters:
      - $ref: '#/components/parameters/programIdParamGet'
      responses:
        200:
          description: OK Session Template Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionTemp'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: sessionTemplate.controller
  /sessionTemplate/getSessionTempById/{session_template_id}:
    get:
      description: Gets an session template by ID
      operationId: getSessionTempById
      parameters:
      - $ref: '#/components/parameters/sessionTempIdParamGet'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionTemp'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: sessionTemplate.controller
  /sessionTemplate/addSessionTemp:
    post:
      description: Creates new session template
      operationId: addSessionTemp
      requestBody:
        description: Add a new session template
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionTemp'
      responses:
        200:
          description: OK Session Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionTemp'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: sessionTemplate.controller
  /sessionTemplate/updateSessionTemp:
    post:
      description: Updates an existing session template
      operationId: updateSessionTemp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionTemp'
      responses:
        200:
          description: OK Session Template Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionTemp'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: sessionTemplate.controller
  /sessionTemplate/deleteSessionTemp:
    delete:
      description: Deletes an existing session template
      operationId: deleteSession
      parameters:
        - $ref: '#/components/parameters/sessionTempIdParamDel'
      responses:
        200:
          description: OK session template Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/sessionTempIdParamDel'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: sessionTemplate.controller

components:
  parameters:
    customerIdParamGet:
      name: customer_id
      in: path
      description: the id of the customer
      required: true
      style: simple
      explode: false
      schema:
        type: string
    customerIdParamDel:
      name: customer_id
      in: query
      description: the id of the customer
      required: true
      style: simple
      explode: false
      schema:
        type: string
    exerciseIdParamPost:
      name: exercise_id
      in: body
      description: the id of the exercise
      required: true
      style: simple
      explode: false
      schema:
        type: string
    exerciseIdParamGet:
      name: exercise_id
      in: path
      description: the id of the exercise
      required: true
      style: simple
      explode: false
      schema:
        type: string
    exerciseIdParamDel:
      name: exercise_id
      in: query
      description: the id of the exercise
      required: true
      style: simple
      explode: false
      schema:
        type: string
    programIdParamGet:
      name: program_id
      in: path
      description: the id of the program
      required: true
      style: simple
      explode: false
      schema:
        type: string
    programIdParamDel:
      name: program_id
      in: query
      description: the id of the program
      required: true
      style: simple
      explode: false
      schema:
        type: string
    sessionIdParamPost:
      name: session_id
      in: body
      description: the id of the session
      required: true
      style: simple
      explode: false
      schema:
        type: string
    sessionIdParamAssign:
      name: assign
      in: body
      description: the id of the session
      required: true
      style: simple
      explode: false
      schema:
        type: Array
        items:
        - $ref: '#/components/parameters/sessionIdParamPost'
        - $ref: '#/components/parameters/exerciseIdParamPost'
    sessionIdParamGet:
      name: session_id
      in: path
      description: the id of the session
      required: true
      style: simple
      explode: false
      schema:
        type: string
    sessionIdParamDel:
      name: session_id
      in: query
      description: the id of the session
      required: true
      style: simple
      explode: false
      schema:
        type: string
    sessionTempIdParamGet:
        name: session_template_id
        in: path
        description: the id of the session template
        required: true
        style: simple
        explode: false
        schema:
          type: string
    sessionTempIdParamDel:
        name: session_template_id
        in: query
        description: the id of the session template
        required: true
        style: simple
        explode: false
        schema:
          type: string
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: object
          readOnly: true
        first_name:
          type: string
          minLength: 1
          maxLength: 100
        last_name:
          type: string
          minLength: 1
          maxLength: 100
        signup_date:
          type: string
          format: date
        gender:
          type: string
          minLength: 1
          maxLength: 50
        dob:
          type: string
          format: date
        activity_level:
          type: string
          minLength: 1
          maxLength: 100
        goal:
          type: string
          minLength: 1
          maxLength: 500
        phone:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        address1:
          type: string
          minLength: 1
          maxLength: 500
        address2:
          type: string
          minLength: 1
          maxLength: 500
        city:
          type: string
          minLength: 1
          maxLength: 100
        zip:
          maximum: 99999
          minimum: 10000
          type: integer
          format: int64
        health_condition:
          type: string
          minLength: 1
          maxLength: 500
        occupation:
          type: string
          minLength: 1
          maxLength: 500
        availability:
          type: string
          minLength: 1
          maxLength: 1000
        commitment:
          type: string
          minLength: 1
          maxLength: 1000
      example:
        zip: 17207
        last_name: lastName
        signup_date: 2000-01-23
        goal: goal
        occupation: occupation
        gender: gender
        address2: address2
        city: city
        address1: address1
        commitment: commitment
        availability: availability
        health_condition: health_condition
        first_name: firstName
        phone: phone
        dob: 2000-01-23
        customer_id: {}
        activity_level: activityLevel
        email: ""
    Measurement:
      type: object
      properties:
        customer_id:
          type: object
          readOnly: true
        measurement_date:
          type: string
          format: date
        weight:
          type: number
          format: double
        height:
          type: number
          format: double
        heartRate1:
          type: number
          format: double
        heartRate2:
          type: number
          format: double
        heartRate3:
          type: number
          format: double
        chest:
          type: number
          format: double
        arm:
          type: number
          format: double
        hips:
          type: number
          format: double
        waist:
          type: number
          format: double
        thigh:
          type: number
          format: double
        dickson_metric:
          type: number
          format: double
      example:
        thigh: 25
        hips: 3.616076749251910
        waist: 70.478
        arm: 15.14
        weight: 0.80082819046101150206595775671303272247314453125
        measurement_date: 2000-01-23
        heartRate1: 50
        dickson_metric: 4.1456080298839363962315474054776132106781005859375
        chest: 5.962133916683182377482808
        customer_id: {}
        heartRate2: 70
        heartRate3: 80
        height: 178.478
    Exercise:
      type: object
      properties:
        exercise_id:
          type: object
        name:
          type: string
          minLength: 1
          maxLength: 500
        description:
          type: string
          minLength: 1
          maxLength: 2000
        equipment_required:
          type: string
          minLength: 1
          maxLength: 1000
        exercise_type:
          type: string
          minLength: 1
          maxLength: 100
        muscles_targeted:
          type: string
          minLength: 1
          maxLength: 1000
        set_break:
          type: integer
          description: the time in seconds to rest between each set
        repetitions:
          type: integer
          description: the count of one atomic set of movement in a set
        sets:
          type: integer
          description: a set is composed of a number of repititions
        exercise_est_duration:
          type: integer
          description: The time allocated to perform exercise
        session:
            type: Object
            description: The assigned session
        exercise_img_url:
            type: string
            description: image that demonstrates the exercise
        exercise_tag:
          type: array
          items: {}
      example:
        exercis_id: {}
        sets: 1
        exercise_tag:
        - ""
        - ""
        exercise_type: exerciseType
        name: name
        exercise_est_duration: 5
        description: description
        equipment_required: equipmentRequired
        set_break: 0
        repetitions: 6
        musclesTargeted: musclesTargeted
    Program:
      type: object
      properties:
        programId:
          type: object
        title:
          type: string
          minLength: 1
          maxLength: 500
        description:
          type: string
          minLength: 1
          maxLength: 5000
        programSDate:
          type: string
          format: date
        programEDate:
          type: string
          format: date
        coachId:
          type: object
      example:
        programId: {}
        title: title of program XXX
        description: description of program XXX
        programSDate: 2019-10-11
        programEDate: 2019-11-11
        coachId: {}
    Session:
        type: object
        properties:
            session_id:
                type: object
            session_name:
                type: string
                minLength: 1
                maxLength: 1000
            session_type:
                type: string
                minLength: 1
                maxLength: 1000
            session_start_date:
                type: string
                format: date
            session_end_date:
                type: string
                format: date
            session_coach_notes:
                type: string
                minLength: 1
                maxLength: 5000
            session_customer_feedback:
                type: string
                minLength: 1
                maxLength: 5000
            exercises:
                type: array
                items:
                    - $ref: '#/components/schemas/Exercise'
            session_tag:
                type: array
                items: {}
            measurement_date:
                type: string
                format: date
        example:
            session_id: {}
            session_type: Exercise Session
            session_start_date: 2019-10-29
            session_end_date: 2019-10-29
            session_coach_notes: Good Job!
            session_customer_feedback: Thank you!
            program_id: {}
            coach_id: {}
            exercise_tag: {}
            measurement_date: 2019-10-29
            customer_id: {}
    SessionTemp:
        type: object
        properties:
            session_template_id:
                type: object
            coach_id:
                type: object
            session_type:
                type: String
                minLength: 1
                maxLength: 100
            session_coach_notes:
                type: String
                minLength: 1
                maxLength: 5000
            exercise_tag:
                type: array
                items: {}
            program_template_id:
                type: object
            
            
